import { Project, ProjectCompany } from "@/types/project";
import { SkillEnum } from "@/types/skill";

export const COMPANY_PROJECT_LIST: Project[] = [
  {
    title: "파트타임스터디 디자인시스템",
    summary: "스터디워크 내 여러 웹앱에서 공통으로 사용하는 UI 컴포넌트들을\nReact 기반으로 구축한 디자인 시스템입니다.",
    image: "/images/projects/PTS_DesignSystem/banner.png",
    imageList: [
      "/images/projects/PTS_DesignSystem/01_Accordion.png",
      "/images/projects/PTS_DesignSystem/02_Button.png",
      "/images/projects/PTS_DesignSystem/03_Popup.png",
      "/images/projects/PTS_DesignSystem/04_Input.png",
    ],
    skills: [
      SkillEnum.React,
      SkillEnum.NextJs,
      SkillEnum.TypeScript,
      SkillEnum.Tailwind,
      SkillEnum.ShadcnUI,
      SkillEnum.HTML,
      SkillEnum.CSS,
      SkillEnum.AWS,
      SkillEnum.Storybook
    ],
    period: {
      start: "2025.04",
      end: "2025.05",
    },
    notionLink: "https://www.notion.so/yunuchoiii/2b5c22b00eb680fcbef0cd5d776d36df?source=copy_link",
    notionId: "2b5c22b00eb680fcbef0cd5d776d36df",
    company: ProjectCompany.PTS,
  },
  {
    title: "파트타임스터디 웹뷰",
    summary: "파트타임스터디 앱 몇가지 주요 기능들을 웹뷰 기반으로 구현하였습니다.",
    image: "/images/projects/PTS_PTS/banner.png",
    imageList: [
      "/images/projects/PTS_PTS/01_캐릭터.png",
      "/images/projects/PTS_PTS/02_스터디그룹_01_메인.png",
      "/images/projects/PTS_PTS/03_스터디그룹_02_상세페이지.png",
      "/images/projects/PTS_PTS/04_디지털커머스.png",
    ],
    skills: [
      SkillEnum.React,
      SkillEnum.NextJs,
      SkillEnum.TypeScript,
      SkillEnum.Tailwind,
      SkillEnum.ReactQuery,
      SkillEnum.Recoil,
      SkillEnum.HTML,
      SkillEnum.CSS,
      SkillEnum.AWS,
    ],
    period: {
      start: "2025.07",
      end: "2025.11",
    },
    notionLink: "https://www.notion.so/yunuchoiii/2b4c22b00eb680c2a5eff2efd18220f4?source=copy_link",
    notionId: "2b4c22b00eb680c2a5eff2efd18220f4",
    company: ProjectCompany.PTS,
    deployedLink: "https://pts-b2c-yunuchoiiii-code.vercel.app/",
  },
  {
    title: "위드파타스 웹뷰",
    summary: "스터디카페 이용자를 위한 앱 내 대부분의 기능들을\n웹뷰 기반으로 구현하였습니다.",
    image: "/images/projects/PTS_WPTS/banner.png",
    imageList: [
      "/images/projects/PTS_WPTS/01_메인.png",
      "/images/projects/PTS_WPTS/02_공부기록.png",
      "/images/projects/PTS_WPTS/03_출금.png",
      "/images/projects/PTS_WPTS/04_디데이&알림함.png",
      "/images/projects/PTS_WPTS/05_마이페이지.png",
    ],
    skills: [
      SkillEnum.React,
      SkillEnum.NextJs,
      SkillEnum.TypeScript,
      SkillEnum.Tailwind,
      SkillEnum.ReactQuery,
      SkillEnum.Recoil,
      SkillEnum.HTML,
      SkillEnum.CSS,
      SkillEnum.AWS,
    ],
    period: {
      start: "2025.05",
      end: "2025.07",
    },
    notionLink: "https://www.notion.so/yunuchoiii/2b4c22b00eb680c2a5eff2efd18220f4?source=copy_link",
    notionId: "2b4c22b00eb680c2a5eff2efd18220f4",
    company: ProjectCompany.PTS,
  },
  {
    title: "메디푸드플랫폼 어드민 & SaaS 서비스",
    summary: "건강검진·식품처방 리포트를 관리하는 내부 어드민과 의료기관용 SaaS 대시보드입니다.\n통계·리포트·운영 기능을 웹 기반으로 구성했습니다.",
    image: "/images/projects/MFP_Admin/banner.png",
    imageList: [
      "/images/projects/MFP_Admin/01_대시보드.png",
      "/images/projects/MFP_Admin/02_상품정보등록.png",
      "/images/projects/MFP_Admin/03_상품고시정보등록.png",
      "/images/projects/MFP_Admin/04_상품옵션등록.png",
      "/images/projects/MFP_Admin/05_상품성분정보등록.png",
      "/images/projects/MFP_Admin/06_상품정보테이블.png",
      "/images/projects/MFP_Admin/07_리포트관리_고객정보등록.png",
      "/images/projects/MFP_Admin/08_리포트관리_검사등록.png",
      "/images/projects/MFP_Admin/09_다운로드분석.png",
      "/images/projects/MFP_Admin/10_연령분석.png",
      "/images/projects/MFP_Admin/11_검사분석.png",
      "/images/projects/MFP_Admin/12_식품처방분석.png",
      "/images/projects/MFP_Admin/13_saas_FAQ.png",
      "/images/projects/MFP_Admin/14_saas요금제플랜.png",
      "/images/projects/MFP_Admin/15_saas_일대일문의_1.png",
      "/images/projects/MFP_Admin/16_saas_일대일문의_2.png",
    ],
    skills: [
      SkillEnum.React,
      SkillEnum.NextJs,
      SkillEnum.TypeScript,
      SkillEnum.Recoil,
      SkillEnum.MUI,
      SkillEnum.HTML,
      SkillEnum.CSS,
    ],
    period: {
      start: "2023.04",
      end: "2024.09",
    },
    notionLink: "https://www.notion.so/yunuchoiii/SaaS-2b5c22b00eb680698e1df87f9c70eb14?source=copy_link",
    notionId: "2b5c22b00eb680698e1df87f9c70eb14",
    company: ProjectCompany.MFP,
  },
  {
    title: "메디푸드플랫폼 이커머스",
    summary: "인사잇 앱 내부의 웹뷰 커머스로 프로젝트입니다.",
    image: "/images/projects/MFP_Ecommerce/banner.png",
    imageList: [
      "/images/projects/MFP_Ecommerce/01_메인대시보드.png",
      "/images/projects/MFP_Ecommerce/02_상품 상세페이지.png",
      "/images/projects/MFP_Ecommerce/03_장바구니.png",
      "/images/projects/MFP_Ecommerce/04_주문페이지.png",
      "/images/projects/MFP_Ecommerce/05_주문내역.png",
      "/images/projects/MFP_Ecommerce/06_교환환불.png",
      "/images/projects/MFP_Ecommerce/07_상품리뷰.png",
      "/images/projects/MFP_Ecommerce/08_마이페이지.png",
    ],
    skills: [
      SkillEnum.React,
      SkillEnum.NextJs,
      SkillEnum.TypeScript,
      SkillEnum.Recoil,
      SkillEnum.MUI,
      SkillEnum.HTML,
      SkillEnum.CSS,
    ],
    period: {
      start: "2023.10",
      end: "2024.09",
    },
    notionLink: "https://www.notion.so/yunuchoiii/2b5c22b00eb680ad9735e5246dafae38?source=copy_link",
    notionId: "2b5c22b00eb680ad9735e5246dafae38",
    company: ProjectCompany.MFP,
  },
];

export const PERSONAL_PROJECT_LIST: Project[] = [
  {
    title: "루틴 아일랜드",
    summary: "작은 습관으로 쌓아올리는 아일랜드.\n루틴 관리 소셜 플랫폼입니다.",
    image: "/images/projects/RoutineIsland/banner.png",
    imageList: [
      "/images/projects/RoutineIsland/01_스크린샷.png",
      "/images/projects/RoutineIsland/02.png",
      "/images/projects/RoutineIsland/03.png",
      "/images/projects/RoutineIsland/04.png",
      "/images/projects/RoutineIsland/05.png",
      "/images/projects/RoutineIsland/06.png",
    ],
    skills: [
      SkillEnum.React,
      SkillEnum.ReactNative,
      SkillEnum.NextJs,
      SkillEnum.TypeScript,
      SkillEnum.Tailwind,
      SkillEnum.HTML,
      SkillEnum.CSS,
      SkillEnum.AWS,
      SkillEnum.ReactQuery,
      SkillEnum.Recoil,
      SkillEnum.ShadcnUI
    ],
    period: {
      start: "2025.12",
      end: "2026.01 (출시 준비중)",
    },
    notionLink: "https://www.notion.so/yunuchoiii/2efc22b00eb68042bdb9ea2d1977b2a9?source=copy_link",
    notionId: "2efc22b00eb68042bdb9ea2d1977b2a9",
    deployedLink: "https://app.routineisland.com/download"
  },
  {
    title: "포트폴리오",
    summary: "디자인부터 개발까지 직접 만든 개인 포트폴리오 웹사이트입니다.\n현재 버전(v2)은 프로젝트 상세 구조와 반응형 UI를 개선했습니다.",
    image: "/images/projects/Portfolio/banner.png",
    imageList: [
      "/images/projects/Portfolio/01.png",
      "/images/projects/Portfolio/02.png",
      "/images/projects/Portfolio/03.png",
      "/images/projects/Portfolio/04.png",
      "/images/projects/Portfolio/05.png",
      "/images/projects/Portfolio/06.png",
      "/images/projects/Portfolio/07.png",
    ],
    skills: [
      SkillEnum.React,
      SkillEnum.NextJs,
      SkillEnum.TypeScript,
      SkillEnum.Tailwind,
      SkillEnum.HTML,
      SkillEnum.CSS,
      SkillEnum.Vercel,
      SkillEnum.Firebase,
    ],
    period: {
      start: "2025.11",
      end: "2025.11",
    },
    notionLink: "https://www.notion.so/yunuchoiii/2b5c22b00eb68019888af9d1c2daf2b8?source=copy_link",
    notionId: "2b5c22b00eb68019888af9d1c2daf2b8",
  },
  {
    title: "JJH 수학학원 홈페이지",
    summary: "학원 소개와 상담 기능을 제공하는 웹사이트입니다.\n기획부터 디자인, 풀스택 개발까지 혼자 진행한 프로젝트입니다.",
    image: "/images/projects/JJH/banner.png",
    imageList: [
      "/images/projects/JJH/01_홈.jpeg",
      "/images/projects/JJH/02_초등교과수학.png",
      "/images/projects/JJH/03_중등교과수학.png",
      "/images/projects/JJH/04_요리수.png",
      "/images/projects/JJH/05_시그마클래스.png",
      "/images/projects/JJH/06_학원소개.png",
      "/images/projects/JJH/07_수업시간:수업료.png",
      "/images/projects/JJH/08_오시는길.png",
      "/images/projects/JJH/09_게시판.png",
      "/images/projects/JJH/10_게시글.png",
      "/images/projects/JJH/11_게시글작성.png",
    ],
    skills: [
      SkillEnum.React,
      SkillEnum.NextJs,
      SkillEnum.TypeScript,
      SkillEnum.Tailwind,
      SkillEnum.NodeJs,
      SkillEnum.MySQL,
      SkillEnum.AWS,
      SkillEnum.Vercel,
      SkillEnum.Figma,
      SkillEnum.HTML,
      SkillEnum.CSS,
    ],
    period: {
      start: "2024.09",
      end: "2025.05",
    },
    notionLink: "https://www.notion.so/yunuchoiii/JJH-2b5c22b00eb6804b9ab7f001dc943819?source=copy_link",
    notionId: "2b5c22b00eb6804b9ab7f001dc943819",
    deployedLink: "https://jjhmath.com/",
  },
  {
    title: "NextMovie",
    summary: "Next.js 학습을 위해 제작한 영화 정보 조회 웹사이트입니다.\n목록·상세·검색 기능으로 Next.js 기본 구조를 익혔습니다.",
    image: "/images/projects/NextMovie/banner.png",
    imageList: [
      "/images/projects/NextMovie/01.jpeg",
      "/images/projects/NextMovie/02.jpeg",
      "/images/projects/NextMovie/03.jpeg",
      "/images/projects/NextMovie/04.png",
    ],
    skills: [
      SkillEnum.React,
      SkillEnum.NextJs,
      SkillEnum.TypeScript,
      SkillEnum.HTML,
      SkillEnum.CSS,
      SkillEnum.Vercel,
    ],
    period: {
      start: "2023.03",
      end: "2023.04",
    },
    notionLink: "https://www.notion.so/yunuchoiii/NextMovie-2b5c22b00eb680db9404d4f3aa837d71?source=copy_link",
    notionId: "2b5c22b00eb680db9404d4f3aa837d71",
    deployedLink: "https://yunu-next-movie.vercel.app/",
  },
  {
    title: "YMDB",
    summary: "React 실습을 위해 제작한 영화 정보 웹사이트입니다.\n리액트의 기본 컴포넌트 구조와 데이터 렌더링을 연습한 프로젝트입니다.",
    image: "/images/projects/YMDB/banner.png",
    imageList: [
      "/images/projects/YMDB/01.png",
      "/images/projects/YMDB/02.png",
    ],
    skills: [
      SkillEnum.React,
      SkillEnum.TypeScript,
      SkillEnum.HTML,
      SkillEnum.CSS,
    ],
    period: {
      start: "2023.03",
      end: "2023.03",
    },
    notionLink: "https://www.notion.so/yunuchoiii/YMDB-2b5c22b00eb68025af9ec9e36d7ccd3c?source=copy_link",
    notionId: "2b5c22b00eb68025af9ec9e36d7ccd3c",
  },
  {
    title: "재고 관리 서비스",
    summary: "공장의 입·출고 데이터를 관리하는 웹 기반 재고관리 시스템입니다.\n대시보드·테이블·차트 UI를 중심으로 전체 디자인 및 프론트 개발을 담당했습니다.",
    image: "/images/projects/Inventory/banner.png",
    imageList: [
      "/images/projects/Inventory/01_dashboard.jpeg",
      "/images/projects/Inventory/02_튜토리얼 시작.jpeg",
      "/images/projects/Inventory/03_튜토리얼.jpeg",
      "/images/projects/Inventory/04_초기설정.jpeg",
      "/images/projects/Inventory/05_입고내역.jpeg",
      "/images/projects/Inventory/06_출고내역.jpeg",
      "/images/projects/Inventory/07_재고 마감.jpeg",
      "/images/projects/Inventory/08_현재고현황.jpeg",
      "/images/projects/Inventory/09_상품 등록.jpeg",
    ],
    skills: [
      SkillEnum.Vue,
      SkillEnum.Vuex,
      SkillEnum.Vuetify,
      SkillEnum.HTML,
      SkillEnum.CSS,
    ],
    period: {
      start: "2023.03",
      end: "2023.03",
    },
    notionLink: "https://www.notion.so/yunuchoiii/2b5c22b00eb680c7a59cffaa0bb5a1e3?source=copy_link",
    notionId: "2b5c22b00eb680c7a59cffaa0bb5a1e3",
  },
  {
    title: "집밥 김선생",
    summary: "식단 계획·영양 분석·레시피 추천을 제공하는 Vue 기반 웹 서비스입니다.\n부트캠프 팀 프로젝트로 개발하여 공모전 동상을 수상했습니다.",
    image: "/images/projects/DIYFood/banner.png",
    imageList: [
      "/images/projects/DIYFood/01_PC - 홈.png",
      "/images/projects/DIYFood/02_PC - 식단계획 1단계.png",
      "/images/projects/DIYFood/03_PC - 식단계획 2단계.png",
      "/images/projects/DIYFood/04_PC - 식단계획 4단계.png",
      "/images/projects/DIYFood/05_PC - 식단계획 5단계.png",
      "/images/projects/DIYFood/06_PC - 나의 식단 계획.png",
      "/images/projects/DIYFood/07_PC - 식단 등록(1).png",
      "/images/projects/DIYFood/08_PC - 식단 분석 - 결과(FullPage).jpeg",
      "/images/projects/DIYFood/09_PC - 식재료 시세.png",
    ],
    skills: [
      SkillEnum.Vue,
      SkillEnum.Bootstrap,
      SkillEnum.HTML,
      SkillEnum.CSS,
    ],
    period: {
      start: "2023.03",
      end: "2023.03",
    },
    notionLink: "https://www.notion.so/yunuchoiii/2b5c22b00eb680b79a62ce3f980bf13a?source=copy_link",
    notionId: "2b5c22b00eb680b79a62ce3f980bf13a",
  },
];